package ru.nikolas_snek.isu_tisbi_xml.domain.repository.models

data class PersonalPlan(
    val persPlanId: Int?,
    val sectId: Int?,
    val sectName: String?,
    val virtSemNumb: Int?,
    val semNumber: Int?,
    val hoursQuant: Int?,
    val typeName: String?,
    val alterGroupTypeId: Int?,
    val alterGroupHeaderId: Int?,
    val isPracticalWork: Int?,
    val countCP: Int?,
    val countResultCP: Int?,
    val CPFinalResult: String?,
    val persPlanIsActual: Int?,
    val spezId: Int?,
    val statusId: Int?,
    val staffName: String?,
    val restConsQuant: Int?,
    val countStaffCP: Int?,
    val staffId: Int?,
    val isStaffUsed: Int?,
    val isRemoteEducation: Int?,
    val isLoadUMMGraduation: Int?,
    val isGroupProc: Int?,
    val isRemoteSect: Int?,
    val mySect: Int?,
    val CP: String?,
    val UMM: String?,
    val planDate: String?,
    val existEduWork: String?,
    val VKR: Boolean?,
    val typePlan: Int?,
    val current: Boolean?,
    val resultSemNumber: String?,
    val checkPoints: List<Checkpoint>? = emptyList()
)

